@startuml
'https://plantuml.com/class-diagram

class RuntimeException <<Unchecked>> #green

Exception <|-- IOException
Exception <|-- RuntimeException

RuntimeException <|-- ValidationException
Exception <|-- CargoNotFoundException
IOException <|-- DatabaseConnectException

@enduml